/* config/config.h.  Generated by configure.  */
/* config/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the `getopt_long' function. */
#define HAVE_GETOPT_LONG 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define the project alias string (name-ver or name-ver-rel). */
#define META_ALIAS "scrub-2.2"

/* Define the project author. */
/* #undef META_AUTHOR */

/* Define the project release date. */
#define META_DATE "2009-07-29"

/* Define the libtool library 'age' version information. */
/* #undef META_LT_AGE */

/* Define the libtool library 'current' version information. */
/* #undef META_LT_CURRENT */

/* Define the libtool library 'revision' version information. */
/* #undef META_LT_REVISION */

/* Define the project name. */
#define META_NAME "scrub"

/* Define the project release. */
#define META_RELEASE "1"

/* Define the project version. */
#define META_VERSION "2.2"

/* Name of package */
#define PACKAGE "scrub"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "2.2"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Expansion of the "bindir" installation directory. */
#define X_BINDIR "/usr/local/bin"

/* Expansion of the "datadir" installation directory. */
#define X_DATADIR "/usr/local/share"

/* Expansion of the "exec_prefix" installation directory. */
#define X_EXEC_PREFIX "/usr/local"

/* Expansion of the "includedir" installation directory. */
#define X_INCLUDEDIR "/usr/local/include"

/* Expansion of the "infodir" installation directory. */
#define X_INFODIR "/usr/local/info"

/* Expansion of the "libdir" installation directory. */
#define X_LIBDIR "/usr/local/lib"

/* Expansion of the "libexecdir" installation directory. */
#define X_LIBEXECDIR "/usr/local/libexec"

/* Expansion of the "localstatedir" installation directory. */
#define X_LOCALSTATEDIR "/usr/local/var"

/* Expansion of the "mandir" installation directory. */
#define X_MANDIR "/usr/local/man"

/* Expansion of the "oldincludedir" installation directory. */
#define X_OLDINCLUDEDIR "/usr/include"

/* Expansion of the "prefix" installation directory. */
#define X_PREFIX "/usr/local"

/* Expansion of the "sbindir" installation directory. */
#define X_SBINDIR "/usr/local/sbin"

/* Expansion of the "sharedstatedir" installation directory. */
#define X_SHAREDSTATEDIR "/usr/local/com"

/* Expansion of the "sysconfdir" installation directory. */
#define X_SYSCONFDIR "/usr/local/etc"

/* Number of bits in a file offset, on hosts where this is settable. */
/* #undef _FILE_OFFSET_BITS */

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */
